CC     = cc
CFLAGS = -std=c99 -Wall -Wextra -O2 $(shell sdl2-config --cflags)
LIBS   = $(shell sdl2-config --libs)

SRC    = src/main.c src/game.c src/platform_sdl2.c
BIN    = breakout

all: $(BIN)

$(BIN): $(SRC) src/game.h src/platform.h
	$(CC) $(CFLAGS) -o $(BIN) $(SRC) $(LIBS)

clean:
	rm -f $(BIN)

run: $(BIN)
	./$(BIN)

.PHONY: all clean run
